/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : -- Unnamed --
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_Gadget00                            0
#define GD_Gadget10                            1
#define GD_Gadget20                            2
#define GD_Gadget30                            3
#define GD_Gadget40                            4
#define GD_Gadget50                            5
#define GD_Gadget60                            6
#define GD_Gadget70                            7
#define GD_Gadget80                            8
#define GD_Gadget90                            9

#define GDX_Gadget00                           0
#define GDX_Gadget10                           1
#define GDX_Gadget20                           2
#define GDX_Gadget30                           3
#define GDX_Gadget40                           4
#define GDX_Gadget50                           5
#define GDX_Gadget60                           6
#define GDX_Gadget70                           7
#define GDX_Gadget80                           8
#define GDX_Gadget90                           9

#define Worldmap_CNT 10

extern struct IntuitionBase *IntuitionBase;
extern struct Library       *GadToolsBase;

extern struct Screen        *Scr;
extern UBYTE                 *PubScreenName;
extern APTR                  VisualInfo;
extern struct Window        *WorldmapWnd;
extern struct Gadget        *WorldmapGList;
extern struct IntuiMessage   WorldmapMsg;
extern struct Gadget        *WorldmapGadgets[10];
extern UWORD                 WorldmapLeft;
extern UWORD                 WorldmapTop;
extern UWORD                 WorldmapWidth;
extern UWORD                 WorldmapHeight;
extern UBYTE                *WorldmapWdt;
extern struct TextAttr       topaz8;
extern struct IntuiText      WorldmapIText[];
extern UWORD                 WorldmapGTypes[];
extern struct NewGadget      WorldmapNGad[];
extern ULONG                 WorldmapGTags[];

extern BOOL zoom_center_set;
extern short zoom_center_lon;
extern short zoom_center_lat;

extern int Gadget00Clicked( void );
extern int Gadget10Clicked( void );
extern int Gadget20Clicked( void );
extern int Gadget30Clicked( void );
extern int Gadget40Clicked( void );
extern int Gadget50Clicked( void );
extern int Gadget60Clicked( void );

extern int SetupScreen( void );
extern void CloseDownScreen( void );
extern void WorldmapRender( void );
extern int HandleWorldmapIDCMP( void );
extern int WorldmapCloseWindow();
extern int WorldmapNewSize();
extern int WorldmapRawKey();
extern int OpenWorldmapWindow( void );
extern void CloseWorldmapWindow( void );

extern void update_gadgets(void);
extern void screen_to_lonlat(struct Window *win, short mx, short my, short *lon, short *lat);
extern void draw_map(struct Window *win);
