/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : -- Unnamed --
 */

#include <exec/types.h>
#include <intuition/intuition.h>
#include <intuition/classes.h>
#include <intuition/classusr.h>
#include <intuition/imageclass.h>
#include <intuition/gadgetclass.h>
#include <libraries/gadtools.h>
#include <graphics/displayinfo.h>
#include <graphics/gfxbase.h>
#include <clib/exec_protos.h>
#include <clib/intuition_protos.h>
#include <clib/gadtools_protos.h>
#include <clib/graphics_protos.h>
#include <clib/utility_protos.h>
#include <string.h>

#include "gui.h"

struct Screen         *Scr = NULL;
UBYTE                 *PubScreenName = NULL;
APTR                   VisualInfo = NULL;
struct Window         *WorldmapWnd = NULL;
struct Gadget         *WorldmapGList = NULL;
struct IntuiMessage    WorldmapMsg;
struct Gadget         *WorldmapGadgets[8];
UWORD                  WorldmapLeft = 10;
UWORD                  WorldmapTop = 15;
UWORD                  WorldmapWidth = 547;
UWORD                  WorldmapHeight = 254;
UBYTE                 *WorldmapWdt = (UBYTE *)"Worldmap";

struct TextAttr topaz8 = {
	( STRPTR )"topaz.font", 8, 0x00, 0x01 };

struct IntuiText WorldmapIText[] = {
	1, 0, JAM1,424, 7, &topaz8, (UBYTE *)"Pan", &WorldmapIText[1],
	1, 0, JAM1,490, 7, &topaz8, (UBYTE *)"Zoom", NULL };

UWORD WorldmapGTypes[] = {
	BUTTON_KIND,
	BUTTON_KIND,
	BUTTON_KIND,
	BUTTON_KIND,
	BUTTON_KIND,
	BUTTON_KIND,
	BUTTON_KIND,
	TEXT_KIND
};

struct NewGadget WorldmapNGad[] = {
	428, 21, 17, 17, (UBYTE *)"N", NULL, GD_Gadget00, PLACETEXT_IN, NULL, (APTR)Gadget00Clicked,
	428, 55, 17, 17, (UBYTE *)"S", NULL, GD_Gadget10, PLACETEXT_IN, NULL, (APTR)Gadget10Clicked,
	411, 38, 17, 17, (UBYTE *)"W", NULL, GD_Gadget20, PLACETEXT_IN, NULL, (APTR)Gadget20Clicked,
	445, 38, 17, 17, (UBYTE *)"E", NULL, GD_Gadget30, PLACETEXT_IN, NULL, (APTR)Gadget30Clicked,
	479, 21, 17, 17, (UBYTE *)"+", NULL, GD_Gadget40, PLACETEXT_IN, NULL, (APTR)Gadget40Clicked,
	513, 21, 17, 17, (UBYTE *)"-", NULL, GD_Gadget50, PLACETEXT_IN, NULL, (APTR)Gadget50Clicked,
	479, 55, 51, 17, (UBYTE *)"Reset", NULL, GD_Gadget60, PLACETEXT_IN, NULL, (APTR)Gadget60Clicked,
	479, 38, 51, 17, NULL, NULL, GD_Gadget70, 0, NULL, NULL
};

ULONG WorldmapGTags[] = {
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(GTTX_Text), (ULONG)"100%", (GTTX_Border), TRUE, (TAG_DONE)
};

int SetupScreen( void )
{
	if ( ! ( Scr = LockPubScreen( PubScreenName )))
		return( 1L );

	if ( ! ( VisualInfo = GetVisualInfo( Scr, TAG_DONE )))
		return( 2L );

	return( 0L );
}

void CloseDownScreen( void )
{
	if ( VisualInfo ) {
		FreeVisualInfo( VisualInfo );
		VisualInfo = NULL;
	}

	if ( Scr        ) {
		UnlockPubScreen( NULL, Scr );
		Scr = NULL;
	}
}

void WorldmapRender( void )
{
	UWORD		offx, offy;

	offx = WorldmapWnd->BorderLeft;
	offy = WorldmapWnd->BorderTop;


	DrawBevelBox( WorldmapWnd->RPort, offx + 403, offy + 2, 136, 78, GT_VisualInfo, VisualInfo, TAG_DONE );
	DrawBevelBox( WorldmapWnd->RPort, offx + 401, offy + 0, 140, 252, GT_VisualInfo, VisualInfo, GTBB_Recessed, TRUE, TAG_DONE );
	DrawBevelBox( WorldmapWnd->RPort, offx + 8, offy + 8, 385, 236, GT_VisualInfo, VisualInfo, GTBB_Recessed, TRUE, TAG_DONE );
	DrawBevelBox( WorldmapWnd->RPort, offx + 0, offy + 0, 401, 251, GT_VisualInfo, VisualInfo, GTBB_Recessed, TRUE, TAG_DONE );
	PrintIText( WorldmapWnd->RPort, WorldmapIText, offx, offy );
}

int HandleWorldmapIDCMP( void )
{
	struct IntuiMessage	*m;
	int			(*func)();
	BOOL			running = TRUE;

	while( m = GT_GetIMsg( WorldmapWnd->UserPort )) {

		CopyMem(( char * )m, ( char * )&WorldmapMsg, (long)sizeof( struct IntuiMessage ));

		GT_ReplyIMsg( m );

		switch ( WorldmapMsg.Class ) {

			case	IDCMP_REFRESHWINDOW:
				GT_BeginRefresh( WorldmapWnd );
				WorldmapRender();
				GT_EndRefresh( WorldmapWnd, TRUE );
				break;

			case	IDCMP_CLOSEWINDOW:
				running = WorldmapCloseWindow();
				break;

			case	IDCMP_NEWSIZE:
				running = WorldmapNewSize();
				break;

			case	IDCMP_RAWKEY:
				running = WorldmapRawKey();
				break;

			case	IDCMP_GADGETUP:
				func = ( void * )(( struct Gadget * )WorldmapMsg.IAddress )->UserData;
				running = func();
				break;

			case IDCMP_MOUSEBUTTONS:
				if (WorldmapMsg.Code == SELECTDOWN)
				{
				    short mx = WorldmapMsg.MouseX;
				    short my = WorldmapMsg.MouseY;
				    if (mx >= WorldmapWnd->BorderLeft &&
				        my >= WorldmapWnd->BorderTop  &&
				        mx <  WorldmapWnd->Width  - WorldmapWnd->BorderRight &&
				        my <  WorldmapWnd->Height - WorldmapWnd->BorderBottom)
				    {
				        screen_to_lonlat(WorldmapWnd, mx, my,
				                         &zoom_center_lon, &zoom_center_lat);
				        zoom_center_set = TRUE;
				        draw(WorldmapWnd);
				    }
				}
				break;

		}
	}
	return( running );
}

int OpenWorldmapWindow( void )
{
	struct NewGadget	ng;
	struct Gadget	*g;
	UWORD		lc, tc;
	UWORD		offx = Scr->WBorLeft, offy = Scr->WBorTop + Scr->RastPort.TxHeight + 1;

	if ( ! ( g = CreateContext( &WorldmapGList )))
		return( 1L );

	for( lc = 0, tc = 0; lc < Worldmap_CNT; lc++ ) {

		CopyMem((char * )&WorldmapNGad[ lc ], (char * )&ng, (long)sizeof( struct NewGadget ));

		ng.ng_VisualInfo = VisualInfo;
		ng.ng_TextAttr   = &topaz8;
		ng.ng_LeftEdge  += offx;
		ng.ng_TopEdge   += offy;

		WorldmapGadgets[ lc ] = g = CreateGadgetA((ULONG)WorldmapGTypes[ lc ], g, &ng, ( struct TagItem * )&WorldmapGTags[ tc ] );

		while( WorldmapGTags[ tc ] ) tc += 2;
		tc++;

		if ( NOT g )
			return( 2L );
	}

	if ( ! ( WorldmapWnd = OpenWindowTags( NULL,
				WA_Left,	WorldmapLeft,
				WA_Top,		WorldmapTop,
				WA_Width,	WorldmapWidth,
				WA_Height,	WorldmapHeight + offy,
				WA_IDCMP,	BUTTONIDCMP|TEXTIDCMP|IDCMP_MOUSEBUTTONS|IDCMP_NEWSIZE|IDCMP_CLOSEWINDOW|IDCMP_RAWKEY|IDCMP_REFRESHWINDOW,
				WA_Flags,	WFLG_DRAGBAR|WFLG_DEPTHGADGET|WFLG_CLOSEGADGET|WFLG_SMART_REFRESH|WFLG_ACTIVATE|WFLG_RMBTRAP,
				WA_Gadgets,	WorldmapGList,
				WA_Title,	WorldmapWdt,
				WA_ScreenTitle,	"GadToolsBox V2.0b � 1991-1993",
				WA_PubScreen,	Scr,
				TAG_DONE )))
	return( 4L );

	GT_RefreshWindow( WorldmapWnd, NULL );

	WorldmapRender();

	return( 0L );
}

void CloseWorldmapWindow( void )
{
	if ( WorldmapWnd        ) {
		CloseWindow( WorldmapWnd );
		WorldmapWnd = NULL;
	}

	if ( WorldmapGList      ) {
		FreeGadgets( WorldmapGList );
		WorldmapGList = NULL;
	}
}

