#ifndef _INCLUDE_test_H
#define _INCLUDE_test_H

/*
 * File generated by StormLink from lib.fd
 * DO NOT EDIT
 * $VER: test.library 1.0
 */
#ifdef __cplusplus
extern "C" {
#endif
#pragma amicall( TestBase, 0x1e, MCC_Query(d0))
#ifdef __cplusplus
};
#endif
#endif
