#ifndef _INCLUDE_WORLDMAP_H
#define _INCLUDE_WORLDMAP_H

/*
 * File generated by StormLink from mcc.fd
 * DO NOT EDIT
 * $VER: worldmap.mcc 1.0 (28-Mar-26)
 */
#ifdef __cplusplus
extern "C" {
#endif
#pragma amicall(WorldmapBase, 0x1e, MCC_Query(d0))
#ifdef __cplusplus
};
#endif
#endif
