#ifndef _INCLUDE_WORLDMAP_H
#define _INCLUDE_WORLDMAP_H

/*
 * File generated by StormLink from mcp.fd
 * DO NOT EDIT
 * $VER: Worldmap.mcp 11.0 (29-Mar-26)
 */
#ifdef __cplusplus
extern "C" {
#endif
#pragma amicall(WorldmapBase, 0x1e, MCP_Query(d0))
#ifdef __cplusplus
};
#endif
#endif
